- name: Install Packages
  import_tasks: Install.yaml
  tags: install
- name: Node Register
  import_tasks: node-register.yaml
  tags: node-register
- name: Docker-login-valut
  import_tasks: docker-login.yaml
  tags: docker-login
- name: Docker-edjruntime 
  import_tasks: docker.yaml
  tags: edjruntime
  
