- name: Install Packages
  import_tasks: Install.yaml
  tags: install
- name: edjx cli configuration
  import_tasks: edjxcli.yaml
  tags: edjxcli
- name: Node Register
  import_tasks: node-register.yaml
  tags: node-register
  #- name: Docker-login-valut
  #import_tasks: docker-login.yaml
  #ignore_errors: yes
  #tags: docker-login
  #- name: Docker-edjruntime 
  #import_tasks: docker.yaml
  #tags: edjruntime
