---
RUNTIME: https://test100.nyc3.digitaloceanspaces.com/runtime/runtime.zip
EDJX_BINARY: https://edjx-alpha.nyc3.digitaloceanspaces.com/edjcli/alpha/linux/amd64/edjx
DOMAIN: validate.edjx.network
bootstrap: no
PACKAGES:
  - make
  - curl
  - gnupg-agent
  - software-properties-common
  - git
  - unzip
  - expect
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - python3.8
  - python3-pip
  - apt-transport-https
  - ca-certificates
    #WRITER_NODE_ID: QmNW9C8hWt8fBuHMN6kV7DCWNKVMG1SNfYAeochyVBj1VX
    #BOOTSTRAP_NODE_ADDRESS: /ip4/64.225.15.186/tcp/5401/p2p/QmNW9C8hWt8fBuHMN6kV7DCWNKVMG1SNfYAeochyVBj1VX
CERTIFICATES: /home/edjruntime/.edjx/runtime/certificates
WORKDIR: /home/edjruntime/.edjx
