---
# defaults file for edjruntime
RUNTIME: https://test100.nyc3.digitaloceanspaces.com/assets/runtime.zip
EDJX_BINARY: https://edjx-alpha.nyc3.digitaloceanspaces.com/edjcli/alpha/linux/amd64/edjx
CERTIFICATES: runtime/certificates
PACKAGES:
  - make
  - curl
  - gnupg-agent
  - software-properties-common
  - git
  - unzip
  - expect
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - python3.8
  - python3-pip
  - apt-transport-https
  - ca-certificates
